services:
  db:
    image: postgres:16-alpine
    container_name: arbati_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: arbati_user
      POSTGRES_PASSWORD: arbati_password
      POSTGRES_DB: arbati
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arbati_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - arbati_network_dev

networks:
  arbati_network_dev:
    driver: bridge

volumes:
  postgres_data_dev:
